homelib/homelib/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'homelib.views.home', name='home'),
    # url(r'^homelib/', include('homelib.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'movies.views.index'),
    url(r'^add_movie', 'movies.views.add_movie_view' ),
    url(r'^add', 'movies.views.add'),
    url(r'^movies', 'movies.views.navigate_to_movies_view')
)

homelib/movies/models.py
from django.db import models

# Create your models here.
# add fields: id, name, genre, description
class Movies(models.Model):
	name = models.CharField(max_length=150)
	genre = models.CharField(max_length=50)
	description = models.CharField(max_length=1500)
	def __unicode__(self):
		return self.name

homelib/movies/forms.py
from django import forms

class MovieAddingForm(forms.Form):
	"""Form for adding a movie to the data base"""
	name = forms.CharField(max_length = 250)
	genre = forms.CharField()
	description = forms.CharField()

homelib/movies/views.py
# Create your views here.
from django.shortcuts import render_to_response, HttpResponseRedirect
from movies.models import Movies
from django.template import RequestContext
from django.core.urlresolvers import reverse
from movies.forms import MovieAddingForm

def index(request):
	full_movies_list = Movies.objects.all()
	return render_to_response('movies/index.html', {'full_movies' : full_movies_list})

def navigate_to_movies_view(request):
	full_movies_list = Movies.objects.all()
	return render_to_response('movies/movies.html', {'full_movies' : full_movies_list})

def add_movie_view(request):
	return render_to_response('movies/add.html', context_instance=RequestContext(request))


	

def add(request):
	if request.method == 'POST':
		form = MovieAddingForm(request.POST)
		if form.is_valid():
			name = form.cleaned_data['name']
			genre = form.cleaned_data['genre']
			description = form.cleaned_data['description']
			new_movie = Movies(name = name, genre = genre, description = description)
			new_movie.save()
			return HttpResponseRedirect('')
	else:
		form = MovieAddingForm()

	return render_to_response('movies/add.html', { 'form' : form, }, context_instance=RequestContext(request))

homelib/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="styles.css" />
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/movies">Movies</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

homelib/templates/movies/add.html
{% extends "base.html" %}

{% block title %}My amazing library{% endblock %}

{% block content %}
<form action = "/add/" method = "post"> {% csrf_token %}
	<table align = "center">
		<thead>
			<tr>
				<th align ="left">
					<label for="id_name">Name:</label> 
				</th>
				<th align ="left">
					<label for="id_genre">Genre:</label> 
				</th>
				<th align ="left">
					<label for="id_description">Description:</label>  
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
				<input id="id_name" type="text" name="name" maxlength="250" />	
				</td>
				<td>
				<input type="text" name="genre" id="id_genre" />	
				</td>
				<td>
				<input type="text" name="description" id="id_description" />
				</td>
			</tr>
			<tr>
				<td>
					<br>
				</td>
			</tr>
			<tr>
				<td colspan = "2" align = "left">
					<a href="/">Go back to movies list</a>	
				</td>
				<td align = "right">
					<input type = "submit" value="Submit" />
				</td>
			</tr>
		</tbody>		
	</table>
</form>
{% endblock %}

homelib/templates/movies/index.html
{% extends "base.html" %}

{% block title %}My amazing library{% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

homelib/templates/movies/movies.html
{% extends "base.html" %}

{% block title %}My amazing library{% endblock %}

{% block content %}
<table border = "1px" align = "center" style = "border-collapse:collapse;">
	<thead>
		<tr>
			<th colspan = "3">
				<h1>Currnet list of movies that were added</h1>
			</th>
		</tr>
		<tr>
			<th>Movie name</th>
			<th>Movie genre</th>
			<th>Movie description</th>
		</tr>
	</thead>
{%for e in full_movies %}
<tr>
<td>
	{{e.name}}
</td>
<td>
	{{e.genre}}
</td>
<td>
	{{e.description}}
</td>
</tr>
{% endfor %}
<table>
	<p align="center"><a href="/add"><strong>Add another movie</strong></a></p>

{% endblock %}